name: FHIR-Validation-Test

# This workflow is used to test any updates to the validation-service repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check out IOPS-FHIR-Test-Scripts 
        uses: actions/checkout@master
        with:
          repository: NHSDigital/IOPS-FHIR-Test-Scripts
          ref: main
          path: IOPS-FHIR-Test-Scripts
          
      - name: Install npm
        run: cd IOPS-FHIR-Test-Scripts ; npm ci
          
      - name: Update FHIR Validator build
        run: mvn clean package

      - name: Run FHIR Validator
        run: 
          nohup java -jar ./target/fhir-validator.jar --terminology.url=https://ontology.nhs.uk/production1/fhir --terminology.authorization.tokenUrl=https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token --terminology.authorization.clientId=${{ secrets.ONTO_CLIENT_ID }} --terminology.authorization.clientSecret=${{ secrets.ONTO_CLIENT_SECRET }} &
          sleep 120
        
      - name: Run Test
        run: cd IOPS-FHIR-Test-Scripts; npm run integration-test
